# Generated by Django 2.2.7 on 2020-02-11 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='person',
            new_name='player',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='group',
            new_name='team',
        ),
    ]
