# Generated by Django 2.2.7 on 2020-03-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournee', '0005_auto_20200302_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='players',
        ),
        migrations.AddField(
            model_name='player',
            name='teams',
            field=models.ManyToManyField(through='tournee.Membership', to='tournee.Team'),
        ),
    ]
