# Generated by Django 2.2.7 on 2020-03-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournee', '0007_auto_20200303_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='date_joined',
            field=models.DateField(blank=True, null=True),
        ),
    ]
