# Generated by Django 2.2.7 on 2020-03-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournee', '0009_auto_20200303_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='teams',
            field=models.ManyToManyField(blank=True, through='tournee.Membership', to='tournee.Team'),
        ),
    ]
