# Generated by Django 2.2.7 on 2020-03-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournee', '0010_auto_20200303_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='teamnames',
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(db_column="Player's_Name", max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='nationality',
            field=models.CharField(db_column='Nationality', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(db_column='Team_Name', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='in_progress',
            field=models.BooleanField(db_column='In_Progress', null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='requirements',
            field=models.CharField(db_column='Requirements', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='rules',
            field=models.CharField(db_column='Rules', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_name',
            field=models.CharField(db_column='Tournament_Name', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournamentline',
            field=models.IntegerField(db_column='TournamentLine', null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='winners',
            field=models.CharField(db_column='Winners', max_length=32, null=True),
        ),
    ]
