# Generated by Django 2.2.7 on 2020-03-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournee', '0011_auto_20200303_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='time_and_date',
            field=models.DateTimeField(db_column='Time_and_Date', null=True),
        ),
    ]
