# Generated by Django 2.2.7 on 2020-03-03 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournee', '0012_auto_20200303_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='in_progress',
        ),
    ]
