# Generated by Django 2.2.7 on 2020-03-04 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournee', '0013_remove_tournament_in_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='captain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tournee.Player'),
        ),
    ]
