# Generated by Django 2.2.7 on 2020-03-05 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournee', '0016_auto_20200305_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='teams',
            field=models.ManyToManyField(blank=True, through='tournee.Seed', to='tournee.Team'),
        ),
        migrations.AlterField(
            model_name='seed',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tournee.Team'),
        ),
    ]
