# Generated by Django 2.2.7 on 2020-03-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournee', '0018_auto_20200305_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='seed',
            name='competing',
            field=models.BooleanField(db_column='Still competing', default=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='current_round',
            field=models.IntegerField(blank=True, db_column='Round', default=0),
        ),
    ]
