# Generated by Django 2.2.7 on 2020-03-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournee', '0019_auto_20200306_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seed',
            name='competing',
            field=models.BooleanField(db_column='Still_Competing', default=True),
        ),
    ]
