# Generated by Django 2.2.7 on 2020-03-15 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournee', '0022_auto_20200312_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='current_round',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='scoreboard',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='tournamentline',
        ),
    ]
